# Generated by Django 5.1.1 on 2026-03-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trello', '0003_alter_lista_id_alter_perfil_id_alter_tablero_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='portada_preset',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
