# Generated by Django 5.1.1 on 2026-03-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trello', '0004_perfil_portada_perfil_portada_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='background',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
    ]
