# Generated by Django 5.1.1 on 2026-03-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trello', '0005_tablero_background_alter_tablero_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablero',
            name='background',
        ),
        migrations.RemoveField(
            model_name='tablero',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='tablero',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='tableros/portadas/'),
        ),
        migrations.AddField(
            model_name='tablero',
            name='portada_preset',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
