# Generated by Django 6.0.2 on 2026-03-06 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trello', '0006_remove_tablero_background_remove_tablero_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TableroPortadaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tableros/portadas/historial/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portadas_historial', to='app_trello.tablero')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
